### ISSUE TITLE
Next.js Remote SPA is not Server Side Rendered

### ISSUE THREAD

**Issue by Kinbaum** [adobe/aem-spa-project-core#40]
### Expected Behaviour

When using the remote SPA feature of AEM along with the components from `@adobe/aem-core-components-react-base` and `@adobe/aem-react-editable-components`, I would expect that SPAs built with Next.js would leverage server side rendering.

### Actual Behaviour

When viewing the source of the page, we can see the content is not generated on the server, but there is a placeholder `aem-container` created:

```html
<!-- view-source:http://localhost:3000 -->
<html lang="en">
    <head>
       <!-- Removed for brevity -->
    </head>
    <body>
        <div id="__next">
            <div>
                <div class="aem-container undefined"></div>
                <div></div>
            </div>
        </div>
        <script src="/_next/static/chunks/react-refresh.js?ts=1626270834385"></script>
        <script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{}},"page":"/","query":{},"buildId":"development","nextExport":true,"autoExport":true,"isFallback":false,"scriptLoader":[]}</script>
    </body>
</html>
```

#### Steps to Reproduce

1. Download the code provided here: [Code Sample.zip](https://github.com/adobe/aem-spa-project-core/files/6816738/Code.Sample.zip)

2. Run `yarn` to install and `yarn dev` to run the app. Should load on localhost:3000
3. On the AEM side under the wknd-app folder create a page, selecting the Next.js template (ensure the latest `spa.project.core` is installed - `1.3.8`).
4. Add a simple title to the page and populate with content
5. Back in the Next.js app, navigate to `view-source:http://localhost:3000` in Google Chrome.
6. Notice that the content is not server side rendered.

**Comment by Kinbaum** [comment]
@sharanyavinod Have you had the opportunity to look into this issue?

**Comment by niekraaijmakers** [comment]
Any error logs coming from nextjs console? We know in principle the spa editor code 1.0 works on SSR. Could be some stuff like fetch needs to be polyfilled.

**Comment by niekraaijmakers** [comment]
Also, I believe we do have a customer who utilizes NextJS + SSR, so I believe it's possible, but I'm waiting for confirmation on this.

**Comment by Kinbaum** [comment]
No errors. The code I provide showcases the issue. Just use the wknd graphql package to wire up the code and you’ll see.

**Comment by HaNdTriX** [comment]
I am pretty new to AEM but afaik you need to use `getServerSideProps`/`getStaticProps` to populate the page with AEM props in order to use `ssr`/`ssg`.

- https://nextjs.org/docs/basic-features/data-fetching
- https://github.com/adobe/aem-spa-project-core/tree/master/ui.apps/src/main/content/jcr_root/apps/spa-project-core/components/remotepagenext

```js
export async function getServerSideProps({ params }) {
   return {
      props: {
        aemPageProps: await getPageDataViaGraphQL(params)
      }
   }
}

export function AEMPage({ aemPageProps }) {
   return (
     <AEMPageComponent {...aemPageProps} />
   )
}
```

**Comment by loganmurphy** [comment]
Here is a link to a bare-bones repo [enter link description here][1]. I tried getting this up and running in codesandbox but there were some issues with the AEM libraries. There is no readme in the repo but steps are simple:
1. clone the repo and cd into the root dir
2. run npm install
3. run npm run dev
4. open the browser to http://localhost:300 (any path works, I have implemented a dynamic Page since AEM pages are dynamic, however we are hard-coding the server-side route/model for the purposes of this example so it'll work regardless of the URL path)

Caveats: There are a lot of workarounds here, I feel like AEM wasn't intended to be used with Next, which is why there is a tutorial for around 20 other CMSs on nextjs.org, but NOT AEM. I am also intermittently getting an error loading the page due to "self not defined" (somehow related to module imports, not sure how to resolve this other than reload the page when I see it, at least it isn't happening with a production build)

**Comment by sowhatdoido** [comment]
Are you guys specifically configuring your nextjs application to use SSR? 
This package exists to interface AEM's CMS with with React components, but I don't believe automatic SSR is a thing. If you look at the AEM documentation on how SSR is handled, it's either you query a serverless function (through Adobe IO) and return the string, or you get the SSR from a node server (how their example recommends you do local development. 
With NextJS you'd either want to deploy it as a standalone server and use AEM just as a headless CMS, or you'd have to deploy a custom server that only generates the html string to be consumed by and rendered in AEM.

**Comment by keepthebyte** [comment]
While this issue is closed - the AEM engineering team is working on an improved integration of Next.js with AEM including in-context editing and SSR/SSG support. The current work-in-progress code can be found here: https://github.com/duynguyen/aem-nextjs-template
